services:
  - type: web
    name: todo-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    branch: main

  - type: web
    name: todo-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    plan: free
    branch: main